repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  # - repo: git://github.com/bridgecrewio/yor
  #   rev: 0.1.199
  #   hooks:
  #     - id: yor
  #       name: yor
  #       description: Yor gets your tagging done.
  #       entry: yor tag -d
  #       language: golang
  #       types: [terraform]
  #       pass_filenames: false
