repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # Use the latest version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: git://github.com/bridgecrewio/yor
    rev: 0.1.199
    hooks:
      - id: yor
        name: yor
        entry: yor tag -d
        args: ["terraform/aws"]
        language: golang
        types: [terraform]
        pass_filenames: false