on: [push]

jobs:
  code-security:
    name: Checkov (CAS) Scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run Checkov scan
        id: checkov
        uses: bridgecrewio/checkov-action@master 
        with:
          directory: .
          soft_fail: true
        # env:
          # PRISMA_API_URL: https://api2.prismacloud.io
        # with:
          # api-key: ${{ secrets.BC_API_KEY }}
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        
        # Results are generated only on a success or failure
        # this is required since GitHub by default won't run the next step
        # when the previous one has failed. Security checks that do not pass will 'fail'.
        # An alternative is to add `continue-on-error: true` to the previous step
        # Or 'soft_fail: true' to checkov.
        if: success() || failure()
        with:
          sarif_file: results.sarif
